version: "2.2"
services:
  frontend:
    image: fesposta/hero-cards-game-ui:1.4
    ports:
      - 3000:5000

  server:
    build: .
    ports:
      - 8080:8080
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: hero-cards-game

  mysql:
    image: mysql:5.7
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: hero-cards-game
volumes:
  mysql-data: