version: "3.7"
services:
  frontend:
    image: fesposta/hero-cards-game-ui:1.5
    ports:
      - 3000:5000

  mysql_db:
    image: mysql:8.0
    restart: always
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_password
      MYSQL_DATABASE_FILE: /run/secrets/db_name
    secrets:
      - db_name
      - db_password

  server:
    build: .
    restart: on-failure
    depends_on:
      - mysql_db
    ports:
      - 8080:8080
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
      MYSQL_DB_FILE: /run/secrets/db_name
    secrets:
      - db_name
      - db_password
      - api_token

secrets:
  db_name:
    file: ./secrets/db_name.txt
  db_password:
    file: ./secrets/db_password.txt

volumes:
  mysql-data: