spring:
  datasource:
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    generate-ddl: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect