spring:
  datasource:
    driver-class-name: "com.mysql.jdbc.Driver"
    url: "jdbc:mysql://${MYSQL_HOST:localhost}:3306/hero-cards-game"
    username: "root"
    password: "secret"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    generate-ddl: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect